apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-manager
  template:
    metadata:
      labels:
        app: book-manager
    spec:
      containers:
      - name: book-manager
        image: nicvi/nicvi-repository:latest
        ports:
        - containerPort: 8000
